[package]
name = "rpga-core"
version = "0.1.0"
edition = "2021"
authors = ["Markku Sukanen"]
license = "MIT OR Apache-2.0"

[dependencies]
rand = "0.8"
dicebag = "0.1"
rpga-rank = { path="../rpga-rank" }
rpga-modifier = { path="../rpga-modifier" }
